language: node_js
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: false
env:
  global:
    secure: LVo/bBB4rbcFmHBcLMySRcR9l5c4G7yBP/Dc4rKiCstd1YjvktWWfvWcZoQOXQHb2rI6c0BzDgnEYGAMNgUoBuZa2Tqh+KbpyfWOeyeROECnGduoTDkg3jFWudW2GVez4yYG5h0JTCuj0xZAnivOxjg18ShnC0xXfSfZmbXYnp1+CrrDz/U9NjPXzF5igamTCihUnZlL2vAOMsBoCoM+jZNvCImp0D1FZH2W7k2tTuOGikoORLcRsw3NYtTikeR8SRMMTtbebPkxql8ipk7scmjW/wEeu/CgziRHFV6Sv9u9t6mo8qRPchQ+j4OIynL0fKQNKqGJ2rpB8CETvnVUpXamOcFs+sOtVawGQFGUYtc0e6gAJ3iHoXSn02YzFgJ7Wj2VtIBmbTcVHe/9+Rx2jA9G4kB1e0J5LXZcnY2FRhI4761mlrre/Prlr2DxyjvJTt+lAQhCKUJADciZBfPoPdPsrtzYYlArRXmVonpJ+9iPHuRSTx86jj3b1dmHuqlekWOvhKwMOkOfrX9VVi2o7InkJCxbrlaJCqthnIDfqIwDDbf7b4t5sT+mLPzxelndSook3sqQAyuhFvbk4ScLo3vyE5HGxp2jiSCPMSzgz2REJ5TdiYuKw+Va4ZKbHQmaHtX5EUGCJIcYMzYTY0gW3MffjNJsgkRNC4HgDgkPmfs=

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

install:
- npm install

script:
- echo $TRAVIS_RELEASE_TAG
- npm run lint
- if test -z "$TRAVIS_TAG"; then npm run make; fi
after_success: npm run publish
